name: kubelint

on:
  push:
    branches: [ "master" ]

jobs:
  kubelint_check:
    runs-on: ubuntu-latest
    steps:
      - name: Scan yamls
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ./helm-source/wordpress/
      - name: Slack Notificationi
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: git-test
          SLACK_COLOR: fa0000
          SLACK_ICON: https://avatars.mds.yandex.net/i?id=ab4d8466aeb3ace0427503c69b9583ec296c3081-5295804-images-thumbs&n=13
          SLACK_MESSAGE: |-
            "Some files are not aproved. Checked with KUBE-LINTER"
          SLACK_TITLE: 'KUBE-LINTER CHECK'
          SLACK_USERNAME: Andrei Baitov
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  slack:
    needs: kubelint_check
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notificationi
        #if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: git-test
          SLACK_COLOR: 00b899
          SLACK_ICON: https://avatars.mds.yandex.net/i?id=ab4d8466aeb3ace0427503c69b9583ec296c3081-5295804-images-thumbs&n=13
          SLACK_MESSAGE: |-
            "All files are aproved. Checked with KUBE-LINTER"
          SLACK_TITLE: 'KUBE-LINTER CHECK'
          SLACK_USERNAME: Andrei Baitov
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} 
